# Database Configuration (read by JDBCUtil)
db.host=db-daugia-java.mysql.database.azure.com
db.name=quan_ly_dau_gia
db.user=linhadmin
db.pass=Linh@611
db.port=3306

# Server Configuration
server.port=8080

# Connection Pool settings
db.pool.max-size=10
db.pool.min-idle=2
db.pool.idle-timeout=30000
db.pool.conn-timeout=20000
db.pool.max-lifetime=1800000
