# Database Configuration (Dành cho JDBCUtil đọc)
db.host=db-daugia-java.mysql.database.azure.com
db.name=quan_ly_dau_gia
db.user=linhadmin
db.pass=Linh@611
db.port=3306

# Server Configuration (Dành cho Web Server của bạn)
server.port=8080

# Các thông số tối ưu cho Connection Pool (Nên thêm vào để quản lý)
db.pool.max-size=10
db.pool.min-idle=2
db.pool.idle-timeout=30000
db.pool.conn-timeout=20000
db.pool.max-lifetime=1800000