package com.bbbc.domain.auction;

import com.bbbc.domain.entity.Entity;

import java.time.Instant;

public final class BidTransaction extends Entity {
    private final String auctionId;
    private final String bidderId;
    private final double amount;
    private final boolean autoGenerated;

    public BidTransaction(String auctionId, String bidderId, double amount, boolean autoGenerated) {
        this.auctionId = auctionId;
        this.bidderId = bidderId;
        this.amount = amount;
        this.autoGenerated = autoGenerated;
    }

    public String getAuctionId() {
        return auctionId;
    }

    public String getBidderId() {
        return bidderId;
    }

    public double getAmount() {
        return amount;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public Instant getTimestamp() {
        return getCreatedAt();
    }
}
