package com.bbbc.client.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.List;
import java.util.Map;

public final class AuctionDetailPanel extends JPanel {
    private final JLabel titleLabel = new JLabel("Auction Detail");
    private final JTextArea infoArea = new JTextArea();
    private final JTextArea historyArea = new JTextArea();
    private final JTextArea eventArea = new JTextArea();
    private final JTextField bidAmountField = new JTextField(8);
    private final JTextField maxBidField = new JTextField(8);
    private final JTextField incrementField = new JTextField("10", 8);
    private final PriceChartPanel priceChartPanel = new PriceChartPanel();

    public AuctionDetailPanel(MainFrame frame) {
        setLayout(new BorderLayout(12, 12));
        infoArea.setEditable(false);
        historyArea.setEditable(false);
        eventArea.setEditable(false);
        infoArea.setMargin(new Insets(8, 8, 8, 8));
        historyArea.setMargin(new Insets(8, 8, 8, 8));
        eventArea.setMargin(new Insets(8, 8, 8, 8));

        JPanel textPanel = new JPanel(new GridLayout(2, 2, 8, 8));
        textPanel.add(wrap("Overview", infoArea));
        textPanel.add(wrap("Bid History", historyArea));
        textPanel.add(wrap("Realtime Events", eventArea));
        textPanel.add(wrap("Price Curve", priceChartPanel));

        add(titleLabel, BorderLayout.NORTH);
        add(textPanel, BorderLayout.CENTER);

        JPanel actions = new JPanel();
        JButton refreshButton = new JButton("Refresh");
        refreshButton.addActionListener(event -> frame.reloadCurrentAuction());
        actions.add(refreshButton);

        actions.add(new JLabel("Bid"));
        actions.add(bidAmountField);
        JButton bidButton = new JButton("Place Bid");
        bidButton.addActionListener(event -> frame.placeBid(bidAmountField.getText().trim()));
        actions.add(bidButton);

        actions.add(new JLabel("Max"));
        actions.add(maxBidField);
        actions.add(new JLabel("Increment"));
        actions.add(incrementField);
        JButton autoBidButton = new JButton("Auto Bid");
        autoBidButton.addActionListener(event -> frame.registerAutoBid(
                maxBidField.getText().trim(),
                incrementField.getText().trim()
        ));
        actions.add(autoBidButton);

        JButton backButton = new JButton("Back");
        backButton.addActionListener(event -> frame.showAuctionList());
        actions.add(backButton);

        add(actions, BorderLayout.SOUTH);
    }

    public void showAuction(Map<String, Object> auction) {
        titleLabel.setText("Auction: " + auction.get("itemName"));
        infoArea.setText("""
                ID: %s
                Type: %s
                Description: %s
                Starting price: %s
                Current price: %s
                Seller: %s
                Leader: %s
                Winner: %s
                State: %s
                Starts at: %s
                Ends at: %s
                """.formatted(
                auction.get("auctionId"),
                auction.get("itemType"),
                auction.get("itemDescription"),
                auction.get("startingPrice"),
                auction.get("currentPrice"),
                auction.get("sellerId"),
                auction.get("leaderBidderId"),
                auction.get("winnerBidderId"),
                auction.get("state"),
                auction.get("startsAt"),
                auction.get("endsAt")
        ));

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> bidHistory = (List<Map<String, Object>>) auction.get("bidHistory");
        StringBuilder historyBuilder = new StringBuilder();
        if (bidHistory != null) {
            for (Map<String, Object> bid : bidHistory) {
                historyBuilder.append(bid.get("timestamp"))
                        .append(" | bidder=")
                        .append(bid.get("bidderId"))
                        .append(" | amount=")
                        .append(bid.get("amount"))
                        .append(" | auto=")
                        .append(bid.get("autoGenerated"))
                        .append(System.lineSeparator());
            }
        }
        historyArea.setText(historyBuilder.toString());
        priceChartPanel.setAuctionData(
                Double.parseDouble(String.valueOf(auction.get("startingPrice"))),
                String.valueOf(auction.get("startsAt")),
                bidHistory
        );
    }

    public void appendEvent(String message) {
        eventArea.append(message + System.lineSeparator());
    }

    public void clearEvents() {
        eventArea.setText("");
    }

    private JPanel wrap(String title, java.awt.Component component) {
        JPanel panel = new JPanel(new BorderLayout(6, 6));
        panel.add(new JLabel(title), BorderLayout.NORTH);
        if (component instanceof PriceChartPanel) {
            panel.add(component, BorderLayout.CENTER);
            return panel;
        }
        panel.add(new JScrollPane(component), BorderLayout.CENTER);
        return panel;
    }
}
