package com.bbbc.common.dto;

import com.bbbc.domain.auction.BidTransaction;

import java.util.LinkedHashMap;
import java.util.Map;

public record BidDto(
        String bidderId,
        double amount,
        boolean autoGenerated,
        String timestamp
) {
    public static BidDto from(BidTransaction bidTransaction) {
        return new BidDto(
                bidTransaction.getBidderId(),
                bidTransaction.getAmount(),
                bidTransaction.isAutoGenerated(),
                bidTransaction.getTimestamp().toString()
        );
    }

    public Map<String, Object> toMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("bidderId", bidderId);
        map.put("amount", amount);
        map.put("autoGenerated", autoGenerated);
        map.put("timestamp", timestamp);
        return map;
    }
}
