package network;

// Lệnh client-server.
public enum Command {
    LOGIN,
    LOGIN_RESULT,

    REGISTER,
    REGISTER_RESULT,

    CREATE_ITEM,
    CREATE_ITEM_RESULT,

    SELECT_ITEMS,
    SELECT_ITEMS_RESULT,

    GET_AUCTION,
    GET_AUCTION_RESULT,

    SET_AUCTION,
    SET_AUCTION_RESULT,

    BID,
    BID_RESULT,
    BALANCE_UPDATE,

    SET_AUTO_BID,
    SET_AUTO_BID_RESULT,

    GET_ALL_AUCTIONS,
    GET_ALL_AUCTIONS_RESULT,

    UPDATE_USER,
    UPDATE_USER_RESULT,

    CHANGE_PASSWORD,
    CHANGE_PASSWORD_RESULT,

    LOGOUT,
    LOGOUT_RESULT,
    FORCE_LOGOUT_MULTIPLE_USER,

    BID_UPDATE,

    ITEMS_UPDATE,

    SET_ALLOW,
    SET_ALLOW_RESULT,

    DELETE_ITEM,
    DELETE_ITEM_RESULT,

    RECHARGE_AMOUNT,
    RECHARGE_AMOUNT_RESULT,

    NOTIFICATION,

    EDIT_ITEM,
    EDIT_ITEM_RESULT,

    GET_SELLER_ITEMS,
    GET_SELLER_ITEMS_RESULT,

    GET_BIDDER_HISTORY,
    GET_BIDDER_HISTORY_RESULT,

    GET_PENDING_DEPOSITS,
    GET_PENDING_DEPOSITS_RESULT,

    APPROVE_DEPOSIT,
    APPROVE_DEPOSIT_RESULT,

    REJECT_DEPOSIT,
    REJECT_DEPOSIT_RESULT,

    DELETE_DEPOSIT_HISTORY,
    DELETE_DEPOSIT_HISTORY_RESULT,

    GET_USER_INFO,
    GET_USER_INFO_RESULT,

    BIDDER_PAY,
    BIDDER_PAY_RESULT,

    NOTIFICATION_NEW_PAY,

    NOTIFICATION_BIDDER_PAY,

    GET_ALL_USERS,
    GET_ALL_USERS_RESULT,

    DELETE_USER,
    DELETE_USER_RESULT,

    FORCE_LOGOUT,

    UPDATE_AUCTION_STATUS,

}
