# Client Configuration
# Set server.ip to the server machine IP when client and server are on different machines
server.ip=20.188.113.2
server.port=8080

cloudinary.cloud_name=dpkehgjjp
cloudinary.api_key=168924452148875
cloudinary.api_secret=JUjgUwOOFx0UegeGWa3VySf-wW4
