# Client Configuration
# L?u ý: N?u ch?y Server và Client trên 2 máy khác nhau, hãy ??i localhost thành ??a ch? IP c?a máy Server
server.ip=192.168.0.105
server.port=8080

cloudinary.cloud_name=dpkehgjjp
cloudinary.api_key=168924452148875
cloudinary.api_secret=JUjgUwOOFx0UegeGWa3VySf-wW4
